### ISSUE TITLE
mistake translate

### ISSUE THREAD

**Issue by alirezaseif28** [midorimici/jqjsconverter#10]
hello 
I am try by this sample
```$('#IsKasrFranshiz621').is(":checked")```

and translate below
```
$('#IsKasrFranshiz621').is(":checked")
```
I hope guds

**Comment by midorimici** [comment]
Thank you for your report.
As in the description, this tool is just a helper and the translated result may be incorrect in some cases.
In that case, please convert the query by yourself.
You can also ask [Chat GPT](https://chat.openai.com/) for help like this:

![image](https://github.com/midorimici/jqjsconverter/assets/60635066/e2f697f4-22f4-4eda-9425-e96265abdfeb)
